name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Backup
      run: |
        timestamp=$(date +%Y%m%d_%H%M%S)
        backup_dir="backup-flipkart-clone-$timestamp"
        mkdir -p $backup_dir
        cp -r src $backup_dir/
        cp .editorconfig $backup_dir/
        cp angular.json $backup_dir/
        cp package.json $backup_dir/
        cp tsconfig*.json $backup_dir/
        echo "Backup created in $backup_dir"
        zip -r "$backup_dir.zip" $backup_dir

    - name: Upload Backup
      uses: actions/upload-artifact@v3
      with:
        name: backup-flipkart-clone
        path: backup-flipkart-clone-*.zip
        retention-days: 5

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
